// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.21.6
// source: panshee/v1/proto/api_wallet.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to Create Wallet function
type CreateWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the user to who wants to create new wallet
	Parent string     `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Wallet *WalletDTO `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateWalletRequest) GetWallet() *WalletDTO {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// Request to Delete Wallet function
type DeleteWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the user to who wants to delete his wallet
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *DeleteWalletRequest) Reset() {
	*x = DeleteWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletRequest) ProtoMessage() {}

func (x *DeleteWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletRequest) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteWalletRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

// Response to Delete Wallet function
type DeleteWalletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// information if deleting wallet was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteWalletResponse) Reset() {
	*x = DeleteWalletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletResponse) ProtoMessage() {}

func (x *DeleteWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletResponse.ProtoReflect.Descriptor instead.
func (*DeleteWalletResponse) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to get wallet function
type GetWalletDTODataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the user to who wants to get his wallets
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *GetWalletDTODataRequest) Reset() {
	*x = GetWalletDTODataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletDTODataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDTODataRequest) ProtoMessage() {}

func (x *GetWalletDTODataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDTODataRequest.ProtoReflect.Descriptor instead.
func (*GetWalletDTODataRequest) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletDTODataRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

// Response of the get wallet function
type GetWalletDTODataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of user's wallets
	Wallets []*WalletDTO `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
}

func (x *GetWalletDTODataResponse) Reset() {
	*x = GetWalletDTODataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletDTODataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletDTODataResponse) ProtoMessage() {}

func (x *GetWalletDTODataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletDTODataResponse.ProtoReflect.Descriptor instead.
func (*GetWalletDTODataResponse) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletDTODataResponse) GetWallets() []*WalletDTO {
	if x != nil {
		return x.Wallets
	}
	return nil
}

// Representation of wallet
type WalletDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Wallet address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// List of tokens in the wallet
	Tokens []*CurrencyDTO `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *WalletDTO) Reset() {
	*x = WalletDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletDTO) ProtoMessage() {}

func (x *WalletDTO) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletDTO.ProtoReflect.Descriptor instead.
func (*WalletDTO) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *WalletDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletDTO) GetTokens() []*CurrencyDTO {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Representation of tokens
type CurrencyDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the token
	TokenName string `protobuf:"bytes,1,opt,name=tokenName,proto3" json:"tokenName,omitempty"`
	// Symbol of the token
	TokenSymbol string `protobuf:"bytes,2,opt,name=tokenSymbol,proto3" json:"tokenSymbol,omitempty"`
	// Amount of tokens in the wallet
	Amount float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Token Price
	PriceUSD float32 `protobuf:"fixed32,4,opt,name=priceUSD,proto3" json:"priceUSD,omitempty"`
	// Price change in % from last 24h
	PriceChangePercentage24H float32 `protobuf:"fixed32,5,opt,name=priceChangePercentage24h,proto3" json:"priceChangePercentage24h,omitempty"`
}

func (x *CurrencyDTO) Reset() {
	*x = CurrencyDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyDTO) ProtoMessage() {}

func (x *CurrencyDTO) ProtoReflect() protoreflect.Message {
	mi := &file_panshee_v1_proto_api_wallet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyDTO.ProtoReflect.Descriptor instead.
func (*CurrencyDTO) Descriptor() ([]byte, []int) {
	return file_panshee_v1_proto_api_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *CurrencyDTO) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *CurrencyDTO) GetTokenSymbol() string {
	if x != nil {
		return x.TokenSymbol
	}
	return ""
}

func (x *CurrencyDTO) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CurrencyDTO) GetPriceUSD() float32 {
	if x != nil {
		return x.PriceUSD
	}
	return 0
}

func (x *CurrencyDTO) GetPriceChangePercentage24H() float32 {
	if x != nil {
		return x.PriceChangePercentage24H
	}
	return 0
}

var File_panshee_v1_proto_api_wallet_proto protoreflect.FileDescriptor

var file_panshee_v1_proto_api_wallet_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x61, 0x6e, 0x73, 0x68, 0x65, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x6e, 0x73, 0x68, 0x65, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x3c,
	0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x6e, 0x73, 0x68, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x54, 0x4f, 0x42,
	0x03, 0xe0, 0x41, 0x02, 0x52, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x32, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x36, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44,
	0x54, 0x4f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0,
	0x41, 0x02, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x54, 0x4f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61,
	0x6e, 0x73, 0x68, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x54, 0x4f, 0x52, 0x07, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x73, 0x22, 0x60, 0x0a, 0x09, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x44, 0x54, 0x4f, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x61, 0x6e, 0x73, 0x68, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x54, 0x4f, 0x52, 0x06, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x44, 0x54, 0x4f, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x55, 0x53, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x55, 0x53, 0x44, 0x12, 0x3a, 0x0a, 0x18, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65,
	0x32, 0x34, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x18, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65,
	0x32, 0x34, 0x68, 0x42, 0x2b, 0x0a, 0x14, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x61, 0x6e, 0x73, 0x68,
	0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0b, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_panshee_v1_proto_api_wallet_proto_rawDescOnce sync.Once
	file_panshee_v1_proto_api_wallet_proto_rawDescData = file_panshee_v1_proto_api_wallet_proto_rawDesc
)

func file_panshee_v1_proto_api_wallet_proto_rawDescGZIP() []byte {
	file_panshee_v1_proto_api_wallet_proto_rawDescOnce.Do(func() {
		file_panshee_v1_proto_api_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_panshee_v1_proto_api_wallet_proto_rawDescData)
	})
	return file_panshee_v1_proto_api_wallet_proto_rawDescData
}

var file_panshee_v1_proto_api_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_panshee_v1_proto_api_wallet_proto_goTypes = []interface{}{
	(*CreateWalletRequest)(nil),      // 0: api.panshee.v1.proto.CreateWalletRequest
	(*DeleteWalletRequest)(nil),      // 1: api.panshee.v1.proto.DeleteWalletRequest
	(*DeleteWalletResponse)(nil),     // 2: api.panshee.v1.proto.DeleteWalletResponse
	(*GetWalletDTODataRequest)(nil),  // 3: api.panshee.v1.proto.GetWalletDTODataRequest
	(*GetWalletDTODataResponse)(nil), // 4: api.panshee.v1.proto.GetWalletDTODataResponse
	(*WalletDTO)(nil),                // 5: api.panshee.v1.proto.WalletDTO
	(*CurrencyDTO)(nil),              // 6: api.panshee.v1.proto.CurrencyDTO
}
var file_panshee_v1_proto_api_wallet_proto_depIdxs = []int32{
	5, // 0: api.panshee.v1.proto.CreateWalletRequest.wallet:type_name -> api.panshee.v1.proto.WalletDTO
	5, // 1: api.panshee.v1.proto.GetWalletDTODataResponse.wallets:type_name -> api.panshee.v1.proto.WalletDTO
	6, // 2: api.panshee.v1.proto.WalletDTO.tokens:type_name -> api.panshee.v1.proto.CurrencyDTO
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_panshee_v1_proto_api_wallet_proto_init() }
func file_panshee_v1_proto_api_wallet_proto_init() {
	if File_panshee_v1_proto_api_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_panshee_v1_proto_api_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWalletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletDTODataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletDTODataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_panshee_v1_proto_api_wallet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_panshee_v1_proto_api_wallet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_panshee_v1_proto_api_wallet_proto_goTypes,
		DependencyIndexes: file_panshee_v1_proto_api_wallet_proto_depIdxs,
		MessageInfos:      file_panshee_v1_proto_api_wallet_proto_msgTypes,
	}.Build()
	File_panshee_v1_proto_api_wallet_proto = out.File
	file_panshee_v1_proto_api_wallet_proto_rawDesc = nil
	file_panshee_v1_proto_api_wallet_proto_goTypes = nil
	file_panshee_v1_proto_api_wallet_proto_depIdxs = nil
}
