// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: panshee/v1/proto/service_panshe_email_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PansheeEmailServiceClient is the client API for PansheeEmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PansheeEmailServiceClient interface {
	// Function to send email
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type pansheeEmailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPansheeEmailServiceClient(cc grpc.ClientConnInterface) PansheeEmailServiceClient {
	return &pansheeEmailServiceClient{cc}
}

func (c *pansheeEmailServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/api.panshee.v1.proto.PansheeEmailService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PansheeEmailServiceServer is the server API for PansheeEmailService service.
// All implementations must embed UnimplementedPansheeEmailServiceServer
// for forward compatibility
type PansheeEmailServiceServer interface {
	// Function to send email
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	mustEmbedUnimplementedPansheeEmailServiceServer()
}

// UnimplementedPansheeEmailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPansheeEmailServiceServer struct {
}

func (UnimplementedPansheeEmailServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedPansheeEmailServiceServer) mustEmbedUnimplementedPansheeEmailServiceServer() {}

// UnsafePansheeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PansheeEmailServiceServer will
// result in compilation errors.
type UnsafePansheeEmailServiceServer interface {
	mustEmbedUnimplementedPansheeEmailServiceServer()
}

func RegisterPansheeEmailServiceServer(s grpc.ServiceRegistrar, srv PansheeEmailServiceServer) {
	s.RegisterService(&PansheeEmailService_ServiceDesc, srv)
}

func _PansheeEmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PansheeEmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.panshee.v1.proto.PansheeEmailService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PansheeEmailServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PansheeEmailService_ServiceDesc is the grpc.ServiceDesc for PansheeEmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PansheeEmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.panshee.v1.proto.PansheeEmailService",
	HandlerType: (*PansheeEmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _PansheeEmailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "panshee/v1/proto/service_panshe_email_service.proto",
}
