apiVersion: apps/v1
kind: Deployment
metadata:
    name: panshee-account-deployment
    labels:
        app: panshee-account
spec:
    replicas: 1
    selector:
        matchLabels:
            app: panshee-account
    template:
        metadata:
            labels:
                app: panshee-account
        spec:
            containers:
                - name: panshee-account
                  image: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                  ports:
                      - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: panshee-account-service
spec:
    selector:
        app: panshee-account
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8081
