apiVersion: apps/v1
kind: Deployment
metadata:
    name: panshee-account-deployment
    labels:
        app: panshee-account
spec:
    replicas: 1
    selector:
        matchLabels:
            app: panshee-account
    template:
        metadata:
            labels:
                app: panshee-account
        spec:
            containers:
                - name: panshee-account
                  image: hudyweas/panshee-account-service:latest
                  ports:
                      - containerPort: 8080
                  env:
                      - name: PANSHEE_ACCOUNT_SERVICE_ADDRESS
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: account-service-http-address
                      - name: PANSHEE_ACCOUNT_SERVICE_GRPC_ADDRESS
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: account-service-grpc-address
                      - name: PANSHEE_ACCOUNT_SERVICE_DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: db-host
                      - name: PANSHEE_ACCOUNT_SERVICE_DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: db-port
                      - name: PANSHEE_ACCOUNT_SERVICE_DB_USER
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: db-user
                      - name: PANSHEE_ACCOUNT_SERVICE_DB_PASSWORD
                        value: ""
                      - name: PANSHEE_ACCOUNT_SERVICE_DB_DBNAME
                        valueFrom:
                            configMapKeyRef:
                                name: panshee-config
                                key: db-name
                      - name: PANSHEE_ACCOUNT_SERVICE_TOKEN_KEY
                        valueFrom:
                            secretKeyRef:
                                name: panshee-config
                                key: panshee-account-token-key
                      - name: PANSHEE_ACCOUNT_SERVICE_ACCESS_TOKEN_DURATION
                        value: 5h
                      - name: PANSHEE_ACCOUNT_SERVICE_REFRESH_TOKEN_DURATION
                        value: 48h
---
apiVersion: v1
kind: Service
metadata:
    name: panshee-account-service
spec:
    selector:
        app: panshee-account
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
